language: php
cache:
  bundler: true
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"
    - "$HOME/.selenium/cache"    
php:
  - 7.1
env:
  - VERSION=8.x-1.x
dist: precise
addons:  
  firefox: 46.0.1
  apt:
    packages:
      - xorg
      - xvfb
      - dbus-x11
      - x11-xkb-utils
      - xfonts-100dpi
      - xfonts-75dpi
      - xfonts-scalable
      - xserver-xorg-core
mysql:
  database: test_cucumber
  username: root
  encoding: utf8
before_install:
  - phpenv config-rm xdebug.ini
  - phpenv rehash
  - composer self-update
  - composer --version

  # Composer Configurations.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/bin:$PATH"
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  # MySQL Configurations.
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"

  # PHP Configurations.
  - echo 'max_execution_time = 1200' >> cucumber.php.ini;
  - echo 'max_input_time = 180' >> cucumber.php.ini;
  - echo 'max_input_vars = 10000' >> cucumber.php.ini;
  - echo 'memory_limit = 2048M' >> cucumber.php.ini;
  - echo 'error_reporting = E_ALL' >> cucumber.php.ini;
  - echo 'post_max_size = 64M' >> cucumber.php.ini;
  - echo 'upload_max_filesize = 32M' >> cucumber.php.ini;
  - echo 'max_file_uploads = 40' >> cucumber.php.ini;
  - echo 'sendmail_path = /bin/true' >> cucumber.php.ini;
  - phpenv config-add cucumber.php.ini
  - phpenv rehash
   
  # Configure and run the virtual display.
  - export DISPLAY=:0
  - sh -e /etc/init.d/xvfb start
  - Xvfb :0 -ac -screen 0 1366x768x24 &
  - sleep 3

  # Run selenium standalone server.
  - SELENIUM="$HOME/.selenium/cache/selenium-server-standalone-2.53.1.jar";
  - if [[ ! -f $SELENIUM ]]; then wget -O $SELENIUM http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar; fi
  - java -jar $SELENIUM -port 4444 > /dev/null 2>&1 &
  - echo "[  OK  ] Starting Selenium on the 4444 port ..."
install:
  - git checkout $TRAVIS_COMMIT
  ## Build with the composer.
  - composer install --no-interaction -vvv
  
  ## Install with drush.
  - cd web
  - drush site-install cucumber --yes --site-name='Cucumber' --account-name=admin --account-pass=dD.123123ddd --account-mail=cucumber@webship.org --db-url="mysql://root:@localhost/test_cucumber" 
  - drush config-set system.performance css.preprocess 0 --yes
  - drush config-set system.performance js.preprocess 0 --yes
  - drush config-set system.logging error_level all --yes
before_script:
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  - sleep 5
script:
  - cd ./profiles/cucumber
  - behat --strict tests/features/cucumber

matrix:
  fast_finish: true